### ISSUE TITLE
GT3 [SCUS-97102] Measurements codes not working on hardware.

### ISSUE THREAD

**Issue by 60fpshacksrock** [CookiePLMonster/Console-Cheat-Codes#10]
Just as it says above.

I have them like this using CheatDevicePS2 1.4.1 and Open PS2 Loader:

Speed and distance units
202F59D8 00000000
Power units
202F59DC 00000002
Torque units
202F59E0 00000002

All other GT3 codes work. Are these for the version with the red case or light blue instead of the retail dark blue?

I know that there are at least two NTSC-U version of the game.

**Comment by CookiePLMonster** [comment]
Hey,

It's possible that maybe the Cheat Device doesn't support cheats in the
'extended' format - try changing the 20 prefix of the memory addresses
(first value) to 00.

niedz., 9 paź 2022 o 04:54 60fpshacksrock ***@***.***>
napisał(a):

**Comment by CookiePLMonster** [comment]
Hey,

It's possible that maybe the Cheat Device doesn't support cheats in the "extended" format - try changing the 20 prefix of the memory addresses (first value) to 00.

**Comment by 60fpshacksrock** [comment]
I will try that and report back. Thanks.

But, if you mean 20 as in 32bit, then yes, it does support that format. But I can still try that.

**Comment by lauti29** [comment]
Hello, it works for me. this is the content of my .cht file: 
---------------------------------------
"Gran Turismo 3 US /ID PBPX_955.03"
Mastercode
902880F8 0C0A1FE6

// Speed and distance units
202F59D8 00000000

// Power units
202F59DC 00000003

// Torque units
202F59E0 00000002
---------------------------------------
(PS2 FAT 39001 - OPNPS2LD-v1.2.0-Beta-1940-d58e721)

**Comment by 60fpshacksrock** [comment]
My apologies for the long delay. It does indeed work on hardware by using OPL's built-in ps2rd. The issue is CheatDevicePS2 1.4.1 and maybe newer versions.
