### ISSUE TITLE
TDU PS2 Trigger codes for OG Hardware

### ISSUE THREAD

**Issue by Pisoj001** [CookiePLMonster/Console-Cheat-Codes#17]
Is it anyway possible to have the manual trigger codes just for the original hardware? I have a codebreaker v7 that works on all games.

**Comment by Pisoj001** [comment]
Anyone? Is it even possible to have the codes for PS2 in codebreaker format?

**Comment by valoslav** [comment]
Use Pnach converter https://www.psx-place.com/resources/pnach-converter-by-pelvicthrustman.1289/
Altough I've tried it on OG hardware and it freezez upon loading when exiting your home/garage,. When only using the R1/R2 & L1/L2 swap codes, it works though. Not sure how to fix this.

**Comment by CookiePLMonster** [comment]
The cheat has been quietly updated last year to fix an issue where it attempted to perform unaligned writes - perhaps it's that?

**Comment by Pisoj001** [comment]
> Use Pnach converter https://www.psx-place.com/resources/pnach-converter-by-pelvicthrustman.1289/
> I've tried it on OG hardware using OPL but it freezes the game on load screen when exiting your home/garage,. When using only the R1/R2 & L1/L2 swap codes, it works though. Not sure how to fix this.

Wow thank you, ill be sure to try this

**Comment by Pisoj001** [comment]
> The cheat has been quietly updated last year to fix an issue where it attempted to perform unaligned writes - perhaps it's that?

Hey, i gotta issue when i go and try to convert it to raw it says i have an Malformed entry.
The entry is: gametitle= Test Drive Unlimited

**Comment by CookiePLMonster** [comment]
The cheat uses a `bytes` cheat format new to PNACH 2.0, that may not be compatible with some older converters.

**Comment by CookiePLMonster** [comment]
> Do you know if the raw code should work with Codebreaker 7.0?

I have no idea, sorry.

**Comment by Pisoj001** [comment]
> > Do you know if the raw code should work with Codebreaker 7.0?
> 
> I have no idea, sorry.

Thanks for the info anyway!

**Comment by CookiePLMonster** [comment]
Please reopen if it's still relevant.
