### ISSUE TITLE
Laptime inaccuracies after you enabled the Metric from Imperial cheat

### ISSUE THREAD

**Issue by kemalkautsar** [CookiePLMonster/Console-Cheat-Codes#18]
Hi,

Ok so I was doing Gran Valley endurance event right. I am using Toyota GT One race version and I usually get around 1.43.000 on my laptime (it's shit I know). Then in the middle of a race I am feeling a bit bored and activate these graphic improvement (because I was using a fresh vanilla installation, no texture mod no nothing on this. also a fresh Duckstation installation as well).

then **_after I enabled some of the cheats, ahem graphic improvement ahem, including the Metric unit. my laptime become 0.52.000ish???_** 

I'm not sure what causes this bug since I enabled 3 cheats altogether

so here's the conditions to replicate this bug/problem:
>Duckstation version 0.1-6892-gf1ff15f9 (dev)
>Gran Turismo USA 1.2
>fresh installation
>enabled cheats:
> - 16:9 Widescreen 2.0
> - 60 FPS (re enable tire smoke)
> - Metric Units

Thanks! big fan btw. thanks for energizing my childhood memories!

**Comment by CookiePLMonster** [comment]
It's probably due to the 60FPS cheat. Since you enabled it in the middle of the race, I wouldn't consider this an issue unless the same happens when you restart the game.

**Comment by kemalkautsar** [comment]
Hi, OK thanks!

Would it affect it as well if I enabled it while not in the middle of the race/before the race? (meaning, if I enabled it I get faster laptime)

**Comment by CookiePLMonster** [comment]
I suspect it's safe to enable anytime outside of the race, except for the pre-race screen (with setups etc.) since at that point it already runs the race code overlay. Obviously though it's the best to just keep it enabled for the entire session.

**Comment by CookiePLMonster** [comment]
Closing this as solved, since we've reached the conclusion it's due to the cheat switching while in race.
