### ISSUE TITLE
Why don't you just add these cheats as defaults in the Duckstation Cheat Manager?

### ISSUE THREAD

**Issue by SecularSteve** [CookiePLMonster/Console-Cheat-Codes#2]
I already put them in for myself, but they're not included by default (running on PAL version):

![Capture](https://user-images.githubusercontent.com/33793273/111393642-6797b780-86b9-11eb-9f96-ffcc19389c88.PNG)

They work fantastically (especially with the PGXP improvements recently, along with the SSAA set to 16x (still running smooth with the re-compiler)).

![1](https://user-images.githubusercontent.com/33793273/111393966-10461700-86ba-11eb-801b-f20762e503d9.PNG)

**Comment by CookiePLMonster** [comment]
Hey,

I guess I just forgot about it! I'll need to look into it.

**Comment by CookiePLMonster** [comment]
All GT1/GT2 cheats are now bundled with Duckstation: https://github.com/stenzek/duckstation/pull/2735
