### ISSUE TITLE
Gran Turismo 2 60 FPS Codes Get Rid of Rear-View Mirror in Bumper Cam View

### ISSUE THREAD

**Issue by Plut0nio** [CookiePLMonster/Console-Cheat-Codes#3]
I have to disable the 60 FPS codes to get my rear-view mirror back, but of course, I'd like to play the game in 60 rather than 30 FPS. Is this an optimization that can de re-enabled, like tire smoke? I've been using the NTSC-U Arcade 1.1 and Sim 1.2 discs. Thanks.

**Comment by CookiePLMonster** [comment]
It'd be surprising if re-enabling the rear view mirror was problematic, I just missed it. I'll make sure to look into that soon.

**Comment by CookiePLMonster** [comment]
Fixed with a19db41469127681f6dce00a1077dfd989a2479e.
