### ISSUE TITLE
Gran Turismo 2 Widescreen patch doesn't have the game go across whole monitor

### ISSUE THREAD

**Issue by Deep4434** [CookiePLMonster/Console-Cheat-Codes#9]
The 16:9 patch didn't  have the go across my whole screen. My screen is 32 inch 1440p monitor.

**Comment by CookiePLMonster** [comment]
The cheat does not aspect the aspect ratio the emulator uses - you still need to set it by yourself.
![image](https://user-images.githubusercontent.com/7947461/163679943-75794c48-c192-4e9e-b2c0-2ca2ebc4cf3d.png)

**Comment by CookiePLMonster** [comment]
Closing as unrelated to the cheat.
